### ISSUE TITLE
Journey Map waypoints render incorrectly

### ISSUE THREAD

**Issue by 4unduck** [ItsPasi/natural-motionblur-fabric#2]
When I have this mod on together with Journey Map, the waypoints render in front of everything, I can see them even through blocks.

**Comment by ItsPasi** [comment]
Seems to be happening for me even when the mod is not installed, I think that's how JourneyMap works. Otherwise, can you see a different result when blur is turned off or on and does graphics fancy vs fabulous show any difference?

**Comment by 4unduck** [comment]
The issue has seem to be fixed itself. Maybe an update in either JourneyMap or your mod fixed it. Thanks for trying to help!

**Comment by 4unduck** [comment]
Nvm, i just had it turned off. But Fabulous fixes it.

**Comment by ItsPasi** [comment]
Can you make a screenshot anyway? It's weird that it works on Fabulous though, since that's where this issue normally occurs with clouds and the world border. Just be aware of that.

**Comment by 4unduck** [comment]
I will only be able to tomorrow, but i will try to explain more clearly for now:
So, normally, waypoints' beams show only if nothing is between them and the player, but when i have Blur turned on, and graphics set to Fancy (Haven't tried lower settings), the beams just fully show regardless if they are blocked by blocks or not.

**Comment by ItsPasi** [comment]
Hmm interesting I was able to reproduce it now. I don't know how to fix it though since it's all the same issue with translucency detection. I might just put a disclaimer on the mod page that if something is buggy to just try Fabulous/Fancy settings until someone knows how to fix this issue. It's related to the first reported issue so I will just keep that one open.
